/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "journalAPI",
            "endpoint": "https://m9wxlwy83j.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ca-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "journalDB-dev",
            "region": "ca-central-1"
        }
    ],
    "aws_user_files_s3_bucket": "journal7f17290ebd0c4e629e7bb57ae9c6aa1301634-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:d1f0e6c7-2553-4cd3-9ab5-7617effaa286",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_FnDhPt4Mb",
    "aws_user_pools_web_client_id": "7j7nop5jp7sg6d7qmik4igkfam",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
